-- ============================================================
-- BigAuction Seed Data
-- Run against: bigauctiontest (local) or your target DB
-- Usage: psql -U akhil -d bigauctiontest -f seed_data.sql
-- ============================================================

-- ==================== CATEGORIES ====================
INSERT INTO categories (name, description, created_at, updated_at)
VALUES
  ('Luxury Watches',      'Authenticated timepieces from the world''s finest watchmakers', NOW(), NOW()),
  ('Designer Handbags',   'Iconic bags from Chanel, Hermès, Louis Vuitton and more',       NOW(), NOW()),
  ('Fine Jewelry',        'Precious gemstone and gold jewellery from luxury maisons',      NOW(), NOW()),
  ('Premium Sneakers',    'Rare and limited-edition athletic and lifestyle footwear',       NOW(), NOW()),
  ('Designer Sunglasses', 'Eyewear from leading fashion houses and optical brands',        NOW(), NOW()),
  ('Luxury Accessories',  'Belts, wallets, scarves and small leather goods',               NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

-- ==================== PRODUCTS ====================
-- We reference categories by name sub-select to stay ID-agnostic.

-- ── LUXURY WATCHES (8 items) ──────────────────────────────────
INSERT INTO products (brand, name, category_id, condition_grade, description, wear_notes,
    source_country, authentication_note, model_name, serial_number, year_of_manufacture,
    authentication_status, certificate_number, provenance, includes_box, includes_dust_bag,
    includes_auth_card, includes_warranty_card, includes_original_receipt, buy_now_price,
    sold, created_at, updated_at)
VALUES

('Rolex', 'Datejust 41 Wimbledon', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'EXCELLENT',
 'A timeless icon in Oystersteel and white gold. The Wimbledon dial features a distinctive grey-green pattern with applied Roman numerals. Fitted with a smooth bezel and Jubilee bracelet.',
 'Light hairlines on bracelet, dial is pristine. Clasp functions perfectly.',
 'Switzerland', 'Authenticated by BigAuction specialist. No signs of service tampering.', 'Datejust 41', 'XXXXXXXX1234', '2021',
 'AUTHENTICATED', 'BA-W-2024-001',
 'Single owner from new. Purchased at Rolex Dubai Mall boutique.',
 TRUE, FALSE, TRUE, TRUE, TRUE, 28500.00, FALSE, NOW(), NOW()),

('Audemars Piguet', 'Royal Oak Offshore Chronograph Blue', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'LIKE_NEW',
 'The Royal Oak Offshore Chronograph in 44mm stainless steel with a stunning blue "Méga Tapisserie" dial. Features a flyback chronograph complication and rubber strap with AP buckle.',
 'No scratches. Sapphire crystal immaculate. Rubber strap shows minimal flex marks.',
 'Switzerland', 'Serial verified against AP international database. Papers intact.', 'Royal Oak Offshore 26400SO', 'BXXXXXXXX98', '2022',
 'AUTHENTICATED', 'BA-W-2024-002',
 'Purchased new in Geneva, serviced once by AP in 2023.',
 TRUE, FALSE, TRUE, TRUE, FALSE, 52000.00, FALSE, NOW(), NOW()),

('Patek Philippe', 'Nautilus 5711 Blue Dial', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'EXCELLENT',
 'The most sought-after Nautilus reference — 5711/1A-010 in stainless steel with the legendary blue gradient dial and horizontal embossed pattern. Self-winding calibre 26-330 S C.',
 'Slight case beveling polish. Dial and hands perfect. Integrated bracelet tight.',
 'Switzerland', 'Patek Philippe Extract of the Archives provided. Movement inspected.', 'Nautilus 5711/1A-010', 'CXXXXXXXX72', '2020',
 'AUTHENTICATED', 'BA-W-2024-003',
 'Originally purchased in Singapore. Exported to UAE by current owner in 2021.',
 TRUE, FALSE, TRUE, TRUE, TRUE, 175000.00, FALSE, NOW(), NOW()),

('Richard Mille', 'RM 11-03 Flyback Chronograph McLaren', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'LIKE_NEW',
 'Limited edition RM 11-03 created in partnership with McLaren. Carbon TPT case with orange accents. Tonneau-shaped case with visible movement through exhibition caseback.',
 'Pristine condition. Original rubber strap never mounted. Spare rubber strap included.',
 'Switzerland', 'Accompanied by full Richard Mille documentation. Movement verified.', 'RM 11-03 McLaren', 'RMXXXXXXXX45', '2022',
 'AUTHENTICATED', 'BA-W-2024-004',
 'Purchased at RM boutique, Dubai International Financial Centre.',
 TRUE, FALSE, TRUE, TRUE, TRUE, 195000.00, FALSE, NOW(), NOW()),

('IWC', 'Portugieser Chronograph Classic', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'GOOD',
 'An elegant vintage-inspired chronograph with cream dial, Arabic numerals and a 42mm stainless steel case. Powered by the in-house 89361 movement.',
 'Minor scratches on lugs. Dial and crystal in excellent shape. Leather strap replaced.',
 'Switzerland', 'Movement examined by certified watchmaker. Functions within COSC spec.', 'Portugieser IW390403', 'IWCXXXXXXX11', '2019',
 'AUTHENTICATED', 'BA-W-2024-005',
 'Second owner. Previous owner was an IWC collector in Abu Dhabi.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 9800.00, FALSE, NOW(), NOW()),

('Omega', 'Speedmaster Moonwatch Professional Co-Axial', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'EXCELLENT',
 'The legendary "Moonwatch" — Speedmaster Professional 42mm with black dial, hesalite crystal, and manual-winding calibre 3861. The only watch to be NASA-certified for all manned missions.',
 'Light wear on Hesalite crystal (normal for model). Bracelet and case well preserved.',
 'Switzerland', 'Omega service history verified. Calibre 3861 confirmed post-2021 update.', 'Speedmaster Moonwatch 310.30.42.50.01.001', 'OMXXXXXXXX67', '2021',
 'AUTHENTICATED', 'BA-W-2024-006',
 'Purchased at Omega boutique, Mall of the Emirates. Full set.',
 TRUE, FALSE, TRUE, TRUE, TRUE, 7500.00, FALSE, NOW(), NOW()),

('Hublot', 'Big Bang Unico Sapphire', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'LIKE_NEW',
 'The iconic Big Bang in a striking all-sapphire 45mm case, revealing the UNICO Chronograph flyback movement in its entirety. A true horological artwork.',
 'No scratches. Sapphire case and exhibition back pristine. Original rubber strap.',
 'Switzerland', 'Hublot authenticity card and certificate of origin present.', 'Big Bang Unico 411.JX.4802.RT', 'HBXXXXXXXX33', '2023',
 'AUTHENTICATED', 'BA-W-2024-007',
 'Unworn display piece from authorised dealer.',
 TRUE, FALSE, TRUE, TRUE, FALSE, 68000.00, FALSE, NOW(), NOW()),

('TAG Heuer', 'Carrera Chronograph Heuer 02', (SELECT id FROM categories WHERE name='Luxury Watches'),
 'EXCELLENT',
 'Sporty yet elegant Carrera in 44mm stainless steel. Heuer 02 in-house movement, COSC chronometer certified, column wheel chronograph with vertical clutch.',
 'Very light case wear. Crown and pushers function crisply. Black leather strap original.',
 'Switzerland', 'TAG Heuer service check performed. All complications verified working.', 'Carrera CBN2A1B.FC6492', 'THXXXXXXXX89', '2021',
 'AUTHENTICATED', 'BA-W-2024-008',
 'Purchased in Riyadh. One owner, watch-enthusiast collector.',
 TRUE, FALSE, TRUE, TRUE, FALSE, 5200.00, FALSE, NOW(), NOW()),

-- ── DESIGNER HANDBAGS (8 items) ──────────────────────────────
('Hermès', 'Birkin 30 Togo Gold with Gold Hardware', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'EXCELLENT',
 'The Hermès Birkin 30 in Gold Togo leather with gold hardware (GHW). One of the most recognisable and coveted bags in the world. Hand-stitched by a single Hermès artisan in Paris.',
 'Slight corner micro-scratches visible under strong light. Interior pristine. Lock and keys unused.',
 'France', 'Authenticated by renowned luxury authentication service. Stitching, leather grain, and hardware hallmarks verified.', 'Birkin 30', 'HRXXXXXXXX01', '2020',
 'AUTHENTICATED', 'BA-B-2024-001',
 'Purchased from Hermès boutique, Dubai Mall. Original receipt and dustbag present.',
 TRUE, TRUE, TRUE, FALSE, TRUE, 38000.00, FALSE, NOW(), NOW()),

('Chanel', 'Classic Double Flap Caviar Black Gold Hardware', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'LIKE_NEW',
 'The Chanel Classic Flap in quilted caviar leather with gold hardware — a wardrobe staple. Interior has the iconic burgundy lambskin lining, zip coin purse and card slots.',
 'Pristine. Chain strap shows no wear. Gold hardware bright.',
 'France', 'Chanel authenticity hologram and serial card present and matching. Verified by Entrupy.', 'Classic Double Flap Medium', 'CNXXXXXXXX55', '2023',
 'AUTHENTICATED', 'BA-B-2024-002',
 'Gift, never carried. Full set including Chanel box.',
 TRUE, TRUE, TRUE, FALSE, FALSE, 11500.00, FALSE, NOW(), NOW()),

('Louis Vuitton', 'Neverfull MM Damier Ebene', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'GOOD',
 'The iconic Louis Vuitton Neverfull MM in Damier Ebene canvas with rose interior. Versatile tote with removable pouch, D-ring and side cinch straps.',
 'Canvas in great shape. Rose interior shows some light transfer. Vachetta handles natural honey patina.',
 'France', 'Date code confirmed and verified against LV authentication database.', 'Neverfull MM', 'LVXXXXXXXX22', '2019',
 'AUTHENTICATED', 'BA-B-2024-003',
 'Pre-owned, single owner, purchased at LV Dubai.',
 FALSE, TRUE, FALSE, FALSE, FALSE, 1450.00, FALSE, NOW(), NOW()),

('Gucci', 'GG Marmont Medium Matelassé Shoulder Bag', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'EXCELLENT',
 'The Gucci GG Marmont in matelassé chevron leather with double G gold-tone hardware. Features a signature V-shaped quilted pattern and an embossed GG symbol.',
 'Minor wear on corners. Interior clean. Gold hardware shows minimal rubbing.',
 'Italy', 'Gucci serial tag and dust bag present. Verified authentic by specialist.', 'GG Marmont Medium', 'GCXXXXXXXX77', '2022',
 'AUTHENTICATED', 'BA-B-2024-004',
 'Purchased at Gucci, Mall of the Emirates. Single owner.',
 FALSE, TRUE, FALSE, FALSE, FALSE, 2200.00, FALSE, NOW(), NOW()),

('Prada', 'Re-Edition 2005 Re-Nylon Bag Black', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'LIKE_NEW',
 'The Prada Re-Edition 2005 in Re-Nylon (recycled ocean plastic) with Saffiano leather trim. Iconic triangular logo plaque and adjustable strap.',
 'No visible wear. Zips smooth. Interior clean.',
 'Italy', 'Prada authentication card, hologram tag, and dustbag included.', 'Re-Edition 2005 1BH204', 'PRXXXXXXXX88', '2023',
 'AUTHENTICATED', 'BA-B-2024-005',
 'Unworn. A gift from Milan that the owner never used.',
 TRUE, TRUE, TRUE, FALSE, FALSE, 1800.00, FALSE, NOW(), NOW()),

('Dior', 'Lady Dior Medium Cannage Lambskin Black', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'EXCELLENT',
 'The quintessential Lady Dior in black lambskin with silver-tone hardware. Features the iconic Cannage quilting, top handles, and a detachable shoulder strap.',
 'Light softening on top handles from carry. Feet clean. Interior perfect.',
 'France', 'Dior authenticity code and care booklet present. Verified by luxury authenticator.', 'Lady Dior Medium', 'DRXXXXXXXX44', '2021',
 'AUTHENTICATED', 'BA-B-2024-006',
 'Purchased at Dior boutique, Four Seasons Riyadh.',
 TRUE, TRUE, TRUE, FALSE, FALSE, 5800.00, FALSE, NOW(), NOW()),

('Bottega Veneta', 'The Pouch Intrecciato Nappa Parakeet', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'LIKE_NEW',
 'Daniel Lee-era BV Pouch in vibrant Parakeet green intrecciato woven nappa. A cult-status piece. Clutch or shoulder carry with detachable strap.',
 'Carried once. Interior and exterior pristine. Weave tight.',
 'Italy', 'BV dust bag and care card present. Verified through BV boutique network.', 'The Pouch 629416', 'BVXXXXXXXX99', '2022',
 'AUTHENTICATED', 'BA-B-2024-007',
 'Purchased at Bottega Veneta, Harrods London by UAE resident.',
 FALSE, TRUE, FALSE, FALSE, FALSE, 3400.00, FALSE, NOW(), NOW()),

('Saint Laurent', 'Loulou Puffer Small Chain Bag Silver', (SELECT id FROM categories WHERE name='Designer Handbags'),
 'EXCELLENT',
 'The YSL Loulou Puffer Small in silver quilted lambskin with a YSL logo buckle and silver chain strap. Compact yet spacious interior with card slots.',
 'No scratches. Chain bright. Interior clean with no marks.',
 'France', 'YSL receipt and care booklet present. Authentication tag verified.', 'Loulou Puffer Small 620333', 'YLXXXXXXXX66', '2022',
 'AUTHENTICATED', 'BA-B-2024-008',
 'Single owner from UAE. Carried on 3 occasions only.',
 FALSE, TRUE, FALSE, FALSE, TRUE, 2950.00, FALSE, NOW(), NOW()),

-- ── FINE JEWELRY (7 items) ───────────────────────────────────
('Cartier', 'Love Bracelet 18k Yellow Gold', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'EXCELLENT',
 'The Cartier Love bracelet in 18k yellow gold — the iconic screw-motif cuff that has been the symbol of eternal love since 1969. Comes with the original screwdriver.',
 'Minor surface scratches consistent with wear. No dents. Hinge and screw mechanism smooth.',
 'France', 'Cartier serial number engraved inside. Authenticity verified by Cartier boutique inspection.', 'Love Bracelet Small Model', 'CTXXXXXXXX11', '2019',
 'AUTHENTICATED', 'BA-J-2024-001',
 'Purchased at Cartier, Dubai Mall. Original receipt present.',
 TRUE, FALSE, TRUE, FALSE, TRUE, 7200.00, FALSE, NOW(), NOW()),

('Tiffany & Co.', 'Diamond Solitaire Engagement Ring Platinum 1.2ct', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'LIKE_NEW',
 'A classic Tiffany Setting solitaire ring in platinum with a round brilliant 1.20ct diamond (F colour, VS1 clarity). The gold standard of engagement rings since 1886.',
 'No scratches. Stone bright and secure. Band pristine.',
 'USA', 'Tiffany & Co. grading certificate and GIA certificate included. Verified by Tiffany boutique.', 'Tiffany Setting 1.20ct Platinum', 'TFXXXXXXXX33', '2022',
 'AUTHENTICATED', 'BA-J-2024-002',
 'Engagement called off. Purchased at Tiffany New York Fifth Avenue.',
 TRUE, FALSE, TRUE, FALSE, TRUE, 22000.00, FALSE, NOW(), NOW()),

('Van Cleef & Arpels', 'Alhambra Long Necklace 20 Motifs Malachite', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'EXCELLENT',
 '20-motif Vintage Alhambra long necklace in 18k yellow gold with malachite stones. The clover motif is one of the most iconic symbols in fine jewellery.',
 'Very light scratches on gold beading. Malachite stones vibrant and unchipped.',
 'France', 'Van Cleef & Arpels certificate and engraved serial on clasp. Boutique verified.', 'Vintage Alhambra Long Necklace 20 Motifs', 'VCAXXXXXXXX55', '2020',
 'AUTHENTICATED', 'BA-J-2024-003',
 'Purchased at VCA Paris. Owner relocating from UAE.',
 TRUE, FALSE, TRUE, FALSE, FALSE, 16500.00, FALSE, NOW(), NOW()),

('Bulgari', 'B.zero1 Ring 18k Rose Gold Four-Band', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'LIKE_NEW',
 'The Bulgari B.zero1 four-band ring in 18k rose gold. Inspired by the Colosseum, the spiral design references Rome''s greatest monument. Size 54.',
 'Worn twice. No scratches. Interior engraving pristine.',
 'Italy', 'Bulgari box, certificate and purchase receipt present.', 'B.zero1 Four-Band Ring 345353', 'BGXXXXXXXX77', '2023',
 'AUTHENTICATED', 'BA-J-2024-004',
 'Purchased at Bulgari, Dubai Mall. Barely worn.',
 TRUE, FALSE, TRUE, FALSE, TRUE, 4800.00, FALSE, NOW(), NOW()),

('Chopard', 'Happy Sport Round 7 Floating Diamonds Bracelet', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'EXCELLENT',
 'A Chopard signature piece — 7 brilliant-cut diamonds floating freely inside a clear sapphire crystal tube set in 18k white gold. 7 diamonds totalling approx. 1.15 carats.',
 'Clasp functions smoothly. Diamonds sparkle bright. Minimal micro-scratches on gold.',
 'Switzerland', 'Chopard authentication certificate and box present. Verified genuine.', 'Happy Sport Bracelet 851697-1001', 'CHPXXXXXXXX22', '2021',
 'AUTHENTICATED', 'BA-J-2024-005',
 'Purchased at Chopard, Emirates Palace Abu Dhabi boutique.',
 TRUE, FALSE, TRUE, FALSE, FALSE, 8900.00, FALSE, NOW(), NOW()),

('Messika', 'Move Addiction Bracelet 18k White Gold Diamonds', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'LIKE_NEW',
 'Messika''s iconic Move Addiction bracelet in 18k white gold with three rows of pavé diamonds that move freely along the bangle. Total diamond weight approx. 1.48 carats.',
 'Minimal wear. Diamonds bright and clean. Box and certificate included.',
 'France', 'Messika serial and certificate of authenticity included.', 'Move Addiction Bracelet', 'MSKXXXXXXXX44', '2023',
 'AUTHENTICATED', 'BA-J-2024-006',
 'Purchased at Messika boutique, Level Shoes Dubai.',
 TRUE, FALSE, TRUE, FALSE, FALSE, 6500.00, FALSE, NOW(), NOW()),

('Graff', 'Diamond Tennis Bracelet 18k White Gold 10ct', (SELECT id FROM categories WHERE name='Fine Jewelry'),
 'EXCELLENT',
 'An exceptional Graff diamond line bracelet in 18k white gold with 42 round brilliant-cut diamonds totalling 10.01 carats. F–G colour, VS clarity. 7 inches.',
 'No visible wear. Diamonds exceptional. Safety clasp in perfect working order.',
 'UK', 'Graff certificate of authenticity with individual stone specifications. Lab cert included.', 'Diamond Line Bracelet 10ct', 'GRFXXXXXXXX99', '2020',
 'AUTHENTICATED', 'BA-J-2024-007',
 'Purchased at Graff, Four Seasons Beirut. Owner resettling in UAE.',
 TRUE, FALSE, TRUE, FALSE, TRUE, 72000.00, FALSE, NOW(), NOW()),

-- ── PREMIUM SNEAKERS (7 items) ────────────────────────────────
('Nike', 'Air Jordan 1 Retro High OG Chicago Lost & Found', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'NEW',
 'The most hyped Jordan 1 colourway of the decade — the "Lost & Found" Chicago recreated with distressed vintage tooling, aged laces and a crinkled aged box. DS (deadstock), never worn, size US 10.',
 'Never worn. Original laces and box tag intact. Aged detailing is intentional by Nike.',
 'USA', 'StockX verified with authentication tag attached to lace.', 'Air Jordan 1 Retro High OG', 'DKXXXXXXXX11', '2022',
 'AUTHENTICATED', 'BA-S-2024-001',
 'Purchased via Nike SNKRS app, shipped to UAE. Never worn.',
 TRUE, FALSE, TRUE, FALSE, FALSE, 850.00, FALSE, NOW(), NOW()),

('New Balance', '990v3 "Made in USA" M990GY3 Grey US 9.5', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'LIKE_NEW',
 'The venerable New Balance 990v3 in classic grey — the "dad shoe" perfected. Made in the USA, ENCAP midsole, pigskin and mesh upper. Size US 9.5. Worn 3 times.',
 'Very light creasing on toebox. Sole pristine. Laces clean.',
 'USA', 'Made in USA label and box verified. No authentication concern.', 'M990GY3', 'NBXXXXXXXX44', '2023',
 'NOT_REQUIRED', NULL,
 'Purchased at NB store NYC.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 480.00, FALSE, NOW(), NOW()),

('Adidas', 'Yeezy Boost 350 V2 Zebra US 11', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'EXCELLENT',
 'The iconic Adidas x Kanye West Yeezy Boost 350 V2 in "Zebra" (CP9654). PRIMEKNIT upper, full-length Boost midsole and distinctive tonal stripe. Size US 11.',
 'Light sole yellowing (normal aging). Primeknit pristine. Box intact.',
 'China', 'Authenticated via Legit Check App and GOAT. StockX tag not included but photos provided.', 'Yeezy Boost 350 V2 Zebra CP9654', 'YZXXXXXXXX88', '2021',
 'AUTHENTICATED', 'BA-S-2024-003',
 'Purchased on StockX by UAE buyer. Size US11.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 620.00, FALSE, NOW(), NOW()),

('Dior', 'B23 High-Top Oblique Canvas White US 42', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'LIKE_NEW',
 'The Dior B23 High-Top in signature Dior Oblique jacquard canvas with a smooth white leather tongue. A sleek luxury-streetwear silhouette from Kim Jones'' debut collection. EU 42.',
 'Worn once indoors. Sole clean. Canvas pristine.',
 'Italy', 'Dior box, dustbag and authenticity card present.', 'B23 High-Top 3SH118YJP H069', 'DRSNXXXXXXX55', '2022',
 'AUTHENTICATED', 'BA-S-2024-004',
 'Purchased at Dior Men, Galeries Lafayette Dubai.',
 TRUE, TRUE, TRUE, FALSE, FALSE, 1350.00, FALSE, NOW(), NOW()),

('Balenciaga', 'Triple S Clear Sole White US 43', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'EXCELLENT',
 'The Balenciaga Triple S in all-white with clear sole — the original "dad sneaker" that defined the chunky trainer era. Layered mesh and leather upper on a triple-stacked sole. EU 43.',
 'Light sole marks from try-on. Uppers clean. Laces original.',
 'Italy', 'Balenciaga box and size sticker present. Verified against authentication guides.', 'Triple S 524039 W09O1 9000', 'BGSNXXXXXXX33', '2022',
 'AUTHENTICATED', 'BA-S-2024-005',
 'Purchased at Balenciaga, Harvey Nichols Riyadh.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 920.00, FALSE, NOW(), NOW()),

('Off-White', 'Out Of Office Low "White Black" US 42', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'LIKE_NEW',
 'The Virgil Abloh-era Off-White Out Of Office (OOO) in white with black contrast heel tab and OW branding. Lightweight canvas upper with vulcanised rubber sole. EU 42.',
 'Worn twice. Light sidewall marks. Upper pristine.',
 'Italy', 'Off-White hologram tag on tongue. Box with tissue paper present.',  'Out Of Office OMIA189C99FAB0030110', 'OWXXXXXXXX77', '2022',
 'AUTHENTICATED', 'BA-S-2024-006',
 'Purchased at SSense. EU resident now based in Dubai.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 780.00, FALSE, NOW(), NOW()),

('Nike', 'Air Max 1 "Travis Scott Cactus Jack" US 9', (SELECT id FROM categories WHERE name='Premium Sneakers'),
 'NEW',
 'The Travis Scott x Nike Air Max 1 "Cactus Jack" in Baroque Brown. Features reversed Swoosh, aged canvas tongue, and oil-stained rope laces. DS, size US 9.',
 'Deadstock, never worn. Box slightly scuffed from storage but interior pristine.',
 'Indonesia', 'StockX verification tag attached. COA card included.',  'Air Max 1 Travis Scott DZ4406-200', 'TSNKXXXXXXX22', '2023',
 'AUTHENTICATED', 'BA-S-2024-007',
 'Purchased through Nike SNKRS US raffle. Shipped to UAE.',
 TRUE, FALSE, TRUE, FALSE, FALSE, 2400.00, FALSE, NOW(), NOW()),

-- ── DESIGNER SUNGLASSES (5 items) ─────────────────────────────
('Ray-Ban', 'Clubmaster Classic Black Gold G-15 Lens', (SELECT id FROM categories WHERE name='Designer Sunglasses'),
 'EXCELLENT',
 'The iconic Ray-Ban Clubmaster in matte black acetate with gold metal detailing and the legendary G-15 green lens. 100% UV protection. Size 51-21-145.',
 'Light surface marks on lenses. Frame and hinges perfect. Case and cleaning cloth included.',
 'Italy', 'Ray-Ban serial on arm verified. Classic collection, no authentication concern.', 'Clubmaster RB3016 W0365', 'RBXXXXXXXX11', '2022',
 'NOT_REQUIRED', NULL,
 'Purchased at Sunglass Hut, Dubai Mall.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 320.00, FALSE, NOW(), NOW()),

('Tom Ford', 'Sasha Cat-Eye Sunglasses Havana Brown', (SELECT id FROM categories WHERE name='Designer Sunglasses'),
 'LIKE_NEW',
 'The Tom Ford FT0764 Sasha in havana brown acetate with gradient brown lenses. A glamorous cat-eye silhouette with TF signature inner keyhole nose bridge. 100% UV protection.',
 'No scratches. Lenses clear. Hinges tight. Pouch included.',
 'Italy', 'Tom Ford authenticity sticker on lens and serial on arm present.', 'FT0764 52G', 'TFXXXXXXXX33', '2023',
 'NOT_REQUIRED', NULL,
 'Purchased at Tom Ford, Dubai Mall. Worn 2 times.',
 FALSE, FALSE, FALSE, FALSE, FALSE, 680.00, FALSE, NOW(), NOW()),

('Cartier', 'Panthère de Cartier Aviator Sunglasses Gold Plated', (SELECT id FROM categories WHERE name='Designer Sunglasses'),
 'EXCELLENT',
 'The Panthère de Cartier aviator-style sunglasses in gold-plated metal with mineral glass lenses. Features the iconic Cartier panther head at the temple tips. Double bridge.',
 'Light nose pad wear. Lenses scratch-free. Gold plating fully intact.',
 'France', 'Cartier serial on inner arm. Original box and case present.', 'Panthère ESW00060 CT0284S', 'CTSUNXXXXXX55', '2021',
 'NOT_REQUIRED', NULL,
 'Purchased at Cartier Abu Dhabi.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 1100.00, FALSE, NOW(), NOW()),

('Dior', 'DiorSignature Butterfly Sunglasses White Gold', (SELECT id FROM categories WHERE name='Designer Sunglasses'),
 'LIKE_NEW',
 'The Dior DiorSignature B1U in white acetate frame with gold CD Diamond logo at temples and light grey lenses. A modern butterfly silhouette with Dior couture DNA.',
 'No visible marks. Lenses perfect. Hinges smooth. Box and certificate included.',
 'Italy', 'Dior authenticity card and serial on arm verified.', 'DiorSignature B1U 95A0', 'DRSUNXXXXXX77', '2023',
 'NOT_REQUIRED', NULL,
 'Purchased at Dior Womenswear, Dubai Mall.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 890.00, FALSE, NOW(), NOW()),

('Gentle Monster', 'Huijer 01 Silver Rimless Shield', (SELECT id FROM categories WHERE name='Designer Sunglasses'),
 'EXCELLENT',
 'Gentle Monster Huijer in a bold silver-tinted rimless shield silhouette with silver mirror lenses. From the "Jentle Garden" collection. A futuristic statement frame favoured by influencers.',
 'Light frame marks. Lenses clean. Original Gentle Monster case.',
 'South Korea', 'Serial on arm present. GM hologram on lens intact.', 'Huijer 01', 'GMXXXXXXXX99', '2022',
 'NOT_REQUIRED', NULL,
 'Purchased at Gentle Monster, Yas Mall Abu Dhabi.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 420.00, FALSE, NOW(), NOW()),

-- ── LUXURY ACCESSORIES (5 items) ──────────────────────────────
('Hermès', 'Reversible H Belt 32mm Fauve / Noir with Gold Buckle', (SELECT id FROM categories WHERE name='Luxury Accessories'),
 'EXCELLENT',
 'The Hermès H belt in 32mm reversible calfskin — Fauve on one side, Noir on the other — with polished gold H buckle. Size 80 (fits waist 28–32"). The most versatile Hermès accessory.',
 'Leather supple and unworn-looking. Minor scuff on gold buckle reverse side. Belt hole edges clean.',
 'France', 'Hermès serial on strap end verified. Dustbag and box included.', 'H Belt Reversible 32mm', 'HRBXXXXXXXX11', '2021',
 'AUTHENTICATED', 'BA-A-2024-001',
 'Purchased at Hermès, Jumeirah boutique.',
 TRUE, TRUE, FALSE, FALSE, FALSE, 920.00, FALSE, NOW(), NOW()),

('Louis Vuitton', 'Monogram Canvas Card Holder Zippy', (SELECT id FROM categories WHERE name='Luxury Accessories'),
 'LIKE_NEW',
 'The LV Zippy Card Holder in classic Monogram canvas with golden zip closure. Holds up to 6 cards plus banknotes. Slim and elegant.',
 'No scratches. Canvas stiff and new. Interior pristine.',
 'France', 'LV date code inside verified. Heat stamp on zip tab present.', 'Zippy Card Holder M62666', 'LVCARDXXXXX33', '2023',
 'NOT_REQUIRED', NULL,
 'Received as gift. Not needed.',
 FALSE, TRUE, FALSE, FALSE, FALSE, 480.00, FALSE, NOW(), NOW()),

('Gucci', 'GG Supreme Canvas Web Bifold Wallet', (SELECT id FROM categories WHERE name='Luxury Accessories'),
 'GOOD',
 'Gucci GG Supreme coated canvas wallet with the iconic Web stripe and interlocking GG logo. Houses 8 card slots, bill compartment and coin zip pocket.',
 'Canvas shows light wear pattern. Leather trim holds colour. Interior clean with no stains.',
 'Italy', 'Gucci serial inside flap verified. Dustbag present.', 'GG Supreme Web Wallet 451268', 'GCWLTXXXXXXX55', '2020',
 'NOT_REQUIRED', NULL,
 'Single owner. Replacing with a newer model.',
 FALSE, TRUE, FALSE, FALSE, FALSE, 380.00, FALSE, NOW(), NOW()),

('Burberry', 'Vintage Check Cashmere Scarf Camel', (SELECT id FROM categories WHERE name='Luxury Accessories'),
 'LIKE_NEW',
 'The Burberry giant Icon scarf in classic camel Vintage Check — 100% cashmere, 190 x 30cm. Lightweight yet warm, the perfect GCC winter-to-summer evening layer.',
 'No pilling. Fringe even and complete. Colour vibrant.',
 'Scotland', 'Burberry label and authentication sticker present.', 'Vintage Check Giant Scarf', 'BBXXXXXXXX77', '2023',
 'NOT_REQUIRED', NULL,
 'Purchased at Burberry, Dubai Mall. Worn once.',
 TRUE, FALSE, FALSE, FALSE, FALSE, 680.00, FALSE, NOW(), NOW()),

('Salvatore Ferragamo', 'Vara Rainbow Leather Belt 25mm Size 75', (SELECT id FROM categories WHERE name='Luxury Accessories'),
 'EXCELLENT',
 'The Ferragamo Vara bow belt in smooth calfskin with multicolor stitching and a golden Vara bow buckle. Size 75 (fits waist 25–29"). A feminine statement accessory.',
 'Light surface marks on buckle. Leather in great shape. No cracking.',
 'Italy', 'Ferragamo serial on back of buckle. Dustbag included.', 'Vara Rainbow Belt 671082', 'SFXXXXXXXX99', '2022',
 'NOT_REQUIRED', NULL,
 'Purchased at Ferragamo, Kingdom Mall Riyadh.',
 FALSE, TRUE, FALSE, FALSE, FALSE, 340.00, FALSE, NOW(), NOW());

-- ==================== VERIFY ====================
SELECT c.name AS category, COUNT(p.id) AS product_count
FROM categories c
LEFT JOIN products p ON p.category_id = c.id
GROUP BY c.name
ORDER BY c.name;
